# Generated by Django 5.0.7 on 2024-12-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_stock_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.BigIntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_data",
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
